name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: component test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Discord success notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          username: ActionCat
          color: '#77fc03'
          description: The build was successful.
          footer: 'Severity: Info'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord error notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          username: ActionCat
          color: '#b50b2d'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: The build failed.
          footer: 'Severity: Error'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: [build]
    name: Fly Deploy
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Discord success notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          username: ActionCat
          color: '#77fc03'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: The pokedex deployment was successfull.
          footer: 'Severity: Info'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord fail notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          username: ActionCat
          color: '#b50b2d'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: The pokedex deployment was not successful.
          footer: 'Severity: Info'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    name: Tag release
    needs: [build]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined commit messages
        env:
          JOINED_COMMITS: ${{ join(github.event.commits.*.message, ' ') }}
        run: echo "$JOINED_COMMITS"
